//
//  This file is part of gmpls-nextworks
//
//  Copyright (C) 2006, 2007, 2008, 2009, 2010, 2011 Nextworks s.r.l.
//
//  @LICENSE_BEGIN@
//  @LICENSE_END@
//
//  Giacomo Bernini       <g DOT bernini AT nextworks DOT it>
//  Gino Carrozzo         <g DOT carrozzo AT nextworks DOT it>
//  Nicola Ciulli         <n DOT ciulli AT nextworks DOT it>
//  Giada Landi           <g DOT landi AT nextworks DOT it>
//  Roberto Monno         <r DOT monno AT nextworks DOT it>
//  Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
//

#ifndef VRM_SPECIFIC_IDL
#define VRM_SPECIFIC_IDL

#include "types.idl"
#include "gmpls.idl"
#include "vrmCommon.idl"

module VRM_SP {

        exception ParamError    { string  what; };
        exception NotCapable    { string  what; };
        exception InternalError { string  what; };
        exception GenericError  { string  what; };
        exception TELNotFound   { string  what; };

        interface Config {
                void init(inout Types::uint32 max_timeout)
                        raises (ParamError, NotCapable,
                                InternalError, GenericError);
        };

        interface VR_Commands {
                void upgradeLink(inout Types::uint32            handle,
                                 in    gmplsTypes::nodeId       localNode,
                                 in    gmplsTypes::nodeId       remoteNode,
                                 in    gmplsTypes::TELinkId     localLinkId,
                                 in    gmplsTypes::TELinkId     remoteLinkId,
                                 in    gmplsTypes::labelId      lblId,
                                 out   Types::uint32            timeout)
                        raises (ParamError, NotCapable,
                                InternalError, GenericError, TELNotFound);
        };
};

#endif
